### PR TITLE
Upgrading lodash

### PR DESCRIPTION
**Pull request by rohitsud**
This is to update lodash to a non-vulnerable version

### CODE REVIEW

**Comment by rohitsud** [comment]
Can someone get this change in and publish it?

**Comment by ghermeto** [comment]
can you update to `4.17.21`? I can merge it.

**Comment by rohitsud** [comment]
> can you update to `4.17.21`? I can merge it.

Done

**Comment by rohitsud** [comment]
@ghermeto Thanks for merging the lodash upgrade. I am not sure about the process followed for release for this repo but it seems that the last release was in 2019.

I created a new PR https://github.com/restify/errors/pull/107 for creating a new release. Please have a look and merge as appropriate.

**Pull request merged**
