### PR TITLE
Upgraded all dependencies

### PR DESCRIPTION
**Pull request by SamuelMarks**
Changed `new Error` object tests to check `.message`; so tests pass once more.

### CODE REVIEW

**Comment by simonepri** [comment]
LGTM
@retrohacker can we merge this?

**Comment by simonepri** [comment]
@SamuelMarks could you list all the other PRs that this will close?
I mean the list of PRs made from @greenkeeperio-bot that could be closed after the merge of this PR.
Thanks 👍

**Comment by SamuelMarks** [comment]
Closes:
https://github.com/restify/errors/pull/35 https://github.com/restify/errors/pull/44 https://github.com/restify/errors/pull/45 https://github.com/restify/errors/pull/47 https://github.com/restify/errors/pull/48 https://github.com/restify/errors/pull/56 https://github.com/restify/errors/pull/57 https://github.com/restify/errors/pull/58 https://github.com/restify/errors/pull/59 https://github.com/restify/errors/pull/60 https://github.com/restify/errors/pull/65 https://github.com/restify/errors/pull/66 https://github.com/restify/errors/pull/67 https://github.com/restify/errors/pull/68 https://github.com/restify/errors/pull/69 https://github.com/restify/errors/pull/70

**Comment by DonutEspresso** [comment]
Thanks @SamuelMarks! Can you provide some context on the changes to the tests? I'm curious which updated dependency caused them to fail?

**Comment by simonepri** [comment]
Any news about that?

**Comment by SamuelMarks** [comment]
I'm not sure @DonutEspresso; I tend to just update all dependencies and tests until they all pass.

**Comment by DonutEspresso** [comment]
@SamuelMarks I brought your PR down locally - I think the breakage is actually due to a bug in the existing tests. The tests were doing a `deepEqual` but somehow chai was passing it, but chai@4.x must be stricter (and arguably correct, IMHO). The updates to the tests you made can be fixed by just applying the same fix to both the two failing tests:

```
-            var parsed = parse(new Error('foobar'), options);
+            var parsed = parse(err, options);
```

It appeared the existing tests were doing a deepEqual but actually passing an incorrect reference. Let me know if you have the time to make the changes! Otherwise, I can take your work here and run with it. 👍   Appreciate the help!

**Comment by simonepri** [comment]
@DonutEspresso It's a good idea to commit the `package-lock` file?

**Comment by simonepri** [comment]
@SamuelMarks @DonutEspresso I've opened a PR with the fix:
https://github.com/SamuelMarks/errors/pull/1
Tests are passing now

**Comment by DonutEspresso** [comment]
@simonepri Looks great! If you are able to open up a PR against this repo, I can merge it in.

**Comment by DonutEspresso** [comment]
Thank you @SamuelMarks @simonepri! Appreciate the help in getting this over the finish line. Apologies for this taking so long!

**Pull request merged**
